"""create usuarios, inventario, cartao e historico

Revision ID: 1b774e1fd1f0
Revises: 
Create Date: 2025-12-26 16:34:01.972536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b774e1fd1f0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cartao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=100), nullable=True),
    sa.Column('titular', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('ultimo_inventario', sa.String(length=50), nullable=True),
    sa.Column('usuario_inventario', sa.String(length=100), nullable=True),
    sa.Column('planta', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('data_inicio', sa.String(length=50), nullable=True),
    sa.Column('data_fim', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('senha', sa.String(length=200), nullable=False),
    sa.Column('nivel', sa.String(length=20), nullable=False),
    sa.Column('planta', sa.String(length=10), nullable=False),
    sa.Column('must_change', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historico_inventario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cartao_id', sa.Integer(), nullable=True),
    sa.Column('numero', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('usuario', sa.String(length=100), nullable=True),
    sa.Column('data', sa.String(length=50), nullable=True),
    sa.Column('mes', sa.String(length=20), nullable=True),
    sa.Column('inventario_id', sa.Integer(), nullable=True),
    sa.Column('planta', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['cartao_id'], ['cartao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historico_inventario')
    op.drop_table('usuarios')
    op.drop_table('inventario')
    op.drop_table('cartao')
    # ### end Alembic commands ###
